[DEV][fdc] added support for the new prepare command syntax
Change-Id: I041619a28f730d774f79feba8cd9ed2c643c9785

diff --git a/utils/fdc b/utils/fdc
--- a/utils/fdc
+++ b/utils/fdc
@@ -97,10 +97,12 @@ case "${command}" in
 		sed_command="s/.*/${identifier} dropped/g"
 		;;
 	PREPARE)
-		format="%s%s"
-		identifier=$2
-		args="${identifier}"
-		sed_command="s#.*STR:'[^']*', STR:'\([^']*\)', STR:'\([^']*\)'.*#new instance created\nsha1: \1\nname: \2#g"
+		format="%s%s%s"
+		folder=$2
+		identification_string=$3
+		args="${folder} ${identification_string}"
+		sed_command[0]="s#.*STR:'PREPARED', STR:'\([^']*\)', STR:'\([^']*\)', STR:'\([^']*\)'.*#new entity in \1 folder created\nsha1: \2\nname: \3#g"
+		sed_command[1]="s#.*STR:'PREPARATION_PROGRESS', STR:'\([^']*\)', STR:'\([^']*\)', STR:'\([^']*\)'.*#\3% done#g"
 		;;
 	START)
 		format="%s%s"
@@ -184,9 +186,9 @@ do
 	then
 		exit ${ERROR_TIMEOUT}
 	fi
-		if [ -n "$(echo ${line} | grep 'STR:.ERROR.')" ];
+	if [ -n "$(echo ${line} | grep 'STR:.ERROR.')" ];
 	then
 		sed_command="s/.*STR:'\([^']*\)'}/firmwared error: \1/g"
 	fi
-	echo ${line} | sed "${sed_command}" | sed "s/'}$//g" | egrep -v '^[[:space:]]*$' || true
+	echo ${line} | sed "${sed_command[0]}" | sed "${sed_command[1]-s/ / /}" | sed "s/'}$//g" | egrep -v '^[[:space:]]*$' || true
 done
